tasks:
  - before: PATH=$HOME/bin:$PATH      
    init: sh ./exercism-setup.sh
    command: exercism configure --workspace=./exercism --token=$EXERCISM_TOKEN

image: gitpod/workspace-rust

vscode:
  extensions:
    - vadimcn.vscode-lldb
    # - mutantdino.resourcemonitor
    - matklad.rust-analyzer
    - tamasfe.even-better-toml
    - serayuzgur.crates
    - vsrs.cross-rust-analyzer
    # - ryanluker.coverage-gutters
    - wayou.vscode-todo-highlight
    - mhutchie.git-graph
