tasks:
  - command: ./exercism-setup.sh --configure $EXERCISM_TOKEN

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - vadimcn.vscode-lldb
    - matklad.rust-analyzer
    - tamasfe.even-better-toml
    - serayuzgur.crates
    - vsrs.cross-rust-analyzer
    - wayou.vscode-todo-highlight
    - mhutchie.git-graph
